name: randexp
description: Create random strings that match a given regular expression.
version: 0.0.1
homepage: https://github.com/Schwusch/randexp.dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  ret: ^0.0.2
  discontinuous_range: ^0.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
